name: "Terraform CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  pull-requests: write

jobs:
  setup_terraform:
    name: "Set up Terraform"
    runs-on: ubuntu-latest
    outputs:
      wd_dev: ${{ steps.WD.outputs.dev }}
      wd_qa: ${{ steps.WD.outputs.qa }}
      wd_prod: ${{ steps.WD.outputs.prod }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
           
      - name: Determine working directory for TF commands
        id: WD 
        uses: dorny/paths-filter@v2
        with:
          list-files: 'json'
          filters: |
            dev:
              - added|deleted|modified: 'non-prod/*/dev/**'
            qa:
              - added|deleted|modified: 'non-prod/*/qa/**'
            prod:
              - added|deleted|modified: 'prod/*/prod/**'

      - run: echo ${{ steps.WD.outputs.changes }}
                
  tf_ci_dev:
    needs: setup_terraform
    if: needs.setup_terraform.outputs.wd_dev == 'true'
    uses: ./.github/workflows/tf_ci_dev.yml
    secrets: inherit

  tf_ci_qa:
    needs: setup_terraform
    if: needs.setup_terraform.outputs.wd_qa == 'true'
    uses: ./.github/workflows/tf_ci_qa.yml
    secrets: inherit

  tf_ci_prod:
    needs: setup_terraform
    if: needs.setup_terraform.outputs.wd_prod == 'true'
    uses: ./.github/workflows/tf_ci_prod.yml
    secrets: inherit

